/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PleaseWork;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test public void testStringCompare() {
    	Library classUnderTest = new Library();
    	
    	String expected = "Howdy world";
    	assertEquals("howdyWorld() should return \"Howdy world\"", expected, classUnderTest.howdyWorld());
    }  
}
