/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PleaseWork;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public String howdyWorld() {
    	return "Howdy world";
    }
}
